### ISSUE TITLE
 Can't start some example launch file

### ISSUE THREAD

**Issue by calvinraun** [OPT4SMART/crazychoir#11]
Hi，we recently ran into a problem, called `ModuleNotFoundError: No module named 'cffirmware'`
We are using:

- ubuntu 20.04
- ROS2 Foxy
- Webots R2022a
When I start `ros2 launch crazychoir_examples formation_webots.launch.py`，it doesn't work，The following is our log file.
`[driver-41] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 2)
[driver-37] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 2)
[driver-45] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 2)
[driver-3] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-13] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-8] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-17] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-21] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-25] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-29] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-33] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-41] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-37] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-45] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 3)
[driver-3] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-13] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-8] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-17] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-21] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-25] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-29] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-33] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-41] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-37] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-45] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 4)
[driver-3] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-13] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-8] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-17] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-21] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-25] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-29] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-33] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-41] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-37] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-45] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 5)
[driver-3] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 6)
[driver-13] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 6)
[driver-8] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 6)
[driver-17] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 6)
[driver-21] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 6)
[driver-25] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 6)
[driver-29] Cannot open file: /tmp/webots-976924-gmyPqD/WEBOTS_SERVER (retry count 6)
[crazychoir_formation_webots_controller_followers-40] [INFO] [1688992781.822426153] [agent_8.controller]: Go!
[crazychoir_formation_webots_controller_leaders-11] [INFO] [1688992781.975849770] [agent_1.controller]: Go!
[crazychoir_formation_webots_controller_followers-24] [INFO] [1688992781.997846415] [agent_4.controller]: Go!
[crazychoir_formation_webots_controller_followers-48] [INFO] [1688992781.998285137] [agent_10.controller]: Go!
[crazychoir_formation_webots_controller_followers-32] [INFO] [1688992782.060363721] [agent_6.controller]: Go!
[crazychoir_formation_webots_controller_followers-44] [INFO] [1688992782.064840630] [agent_9.controller]: Go!
[crazychoir_formation_webots_trajectory-7] [INFO] [1688992782.069662405] [agent_0.trajectory]: FullState reference 0 started
[crazychoir_formation_webots_trajectory-7] [WARN] [1688992782.079272132] [agent_0.trajectory]: No trajectory parameters passed by argument.
[crazychoir_formation_webots_trajectory-7] [WARN] [1688992782.079797898] [agent_0.trajectory]: Wait for topic: "/agent_0/traj_params"
[crazychoir_formation_webots_trajectory-7] [INFO] [1688992782.080270826] [agent_0.trajectory]: Go!
[crazychoir_formation_webots_trajectory-12] [INFO] [1688992782.082571427] [agent_1.trajectory]: FullState reference 1 started
[crazychoir_formation_webots_controller_followers-36] [INFO] [1688992782.085308533] [agent_7.controller]: Go!
[crazychoir_formation_webots_trajectory-12] [WARN] [1688992782.088564997] [agent_1.trajectory]: No trajectory parameters passed by argument.
[crazychoir_formation_webots_trajectory-12] [WARN] [1688992782.089079896] [agent_1.trajectory]: Wait for topic: "/agent_1/traj_params"
[crazychoir_formation_webots_trajectory-12] [INFO] [1688992782.094907995] [agent_1.trajectory]: Go!
[crazychoir_formation_webots_controller_followers-16] [INFO] [1688992782.111265151] [agent_2.controller]: Go!
[crazychoir_formation_webots_controller_followers-28] [INFO] [1688992782.221470765] [agent_5.controller]: Go!
[crazychoir_formation_webots_controller_followers-20] [INFO] [1688992782.247332739] [agent_3.controller]: Go!
[crazychoir_formation_webots_controller_leaders-6] [INFO] [1688992782.249049223] [agent_0.controller]: Go!
[driver-21] Traceback (most recent call last):
[driver-21]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-21]     import cffirmware
[driver-21] ModuleNotFoundError: No module named 'cffirmware'
[driver-21] 
[driver-21] During handling of the above exception, another exception occurred:
[driver-21] 
[driver-21] Traceback (most recent call last):
[driver-21]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-21]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-21]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-21]     from .motor_ctrl import MotorCtrl
[driver-21]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-21]     from ..utils import cffirmware
[driver-21]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-21]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-21] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-21] terminate called after throwing an instance of 'std::runtime_error'
[driver-21]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-37] Traceback (most recent call last):
[driver-37]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-37]     import cffirmware
[driver-37] ModuleNotFoundError: No module named 'cffirmware'
[driver-37] 
[driver-37] During handling of the above exception, another exception occurred:
[driver-37] 
[driver-37] Traceback (most recent call last):
[driver-37]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-37]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-37]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-37]     from .motor_ctrl import MotorCtrl
[driver-37]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-37]     from ..utils import cffirmware
[driver-37]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-37]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-37] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-37] terminate called after throwing an instance of 'std::runtime_error'
[driver-37]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-33] Traceback (most recent call last):
[driver-33]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-33]     import cffirmware
[driver-33] ModuleNotFoundError: No module named 'cffirmware'
[driver-33] 
[driver-33] During handling of the above exception, another exception occurred:
[driver-33] 
[driver-33] Traceback (most recent call last):
[driver-33]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-33]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-33]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-33]     from .motor_ctrl import MotorCtrl
[driver-33]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-33]     from ..utils import cffirmware
[driver-33]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-33]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-33] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-33] terminate called after throwing an instance of 'std::runtime_error'
[driver-33]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-29] Traceback (most recent call last):
[driver-29]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-29]     import cffirmware
[driver-29] ModuleNotFoundError: No module named 'cffirmware'
[driver-29] 
[driver-29] During handling of the above exception, another exception occurred:
[driver-29] 
[driver-29] Traceback (most recent call last):
[driver-29]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-29]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-29]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-29]     from .motor_ctrl import MotorCtrl
[driver-29]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-29]     from ..utils import cffirmware
[driver-29]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-29]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-29] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-29] terminate called after throwing an instance of 'std::runtime_error'
[driver-29]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-25] Traceback (most recent call last):
[driver-25]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-25]     import cffirmware
[driver-25] ModuleNotFoundError: No module named 'cffirmware'
[driver-25] 
[driver-25] During handling of the above exception, another exception occurred:
[driver-25] 
[driver-25] Traceback (most recent call last):
[driver-25]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-25]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-25]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-25]     from .motor_ctrl import MotorCtrl
[driver-25]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-25]     from ..utils import cffirmware
[driver-25]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-25]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-25] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-25] terminate called after throwing an instance of 'std::runtime_error'
[driver-25]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-13] Traceback (most recent call last):
[driver-13]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-13]     import cffirmware
[driver-13] ModuleNotFoundError: No module named 'cffirmware'
[driver-13] 
[driver-13] During handling of the above exception, another exception occurred:
[driver-13] 
[driver-13] Traceback (most recent call last):
[driver-13]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-13]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-13]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-13]     from .motor_ctrl import MotorCtrl
[driver-13]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-13]     from ..utils import cffirmware
[driver-13]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-13]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-13] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-13] terminate called after throwing an instance of 'std::runtime_error'
[driver-13]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-17] Traceback (most recent call last):
[driver-17]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-17]     import cffirmware
[driver-17] ModuleNotFoundError: No module named 'cffirmware'
[driver-17] 
[driver-17] During handling of the above exception, another exception occurred:
[driver-17] 
[driver-17] Traceback (most recent call last):
[driver-17]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-17]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-17]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-17]     from .motor_ctrl import MotorCtrl
[driver-17]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-17]     from ..utils import cffirmware
[driver-17]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-17]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-17] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-17] terminate called after throwing an instance of 'std::runtime_error'
[driver-17]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-45] Traceback (most recent call last):
[driver-45]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-45]     import cffirmware
[driver-45] ModuleNotFoundError: No module named 'cffirmware'
[driver-45] 
[driver-45] During handling of the above exception, another exception occurred:
[driver-45] 
[driver-45] Traceback (most recent call last):
[driver-45]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-45]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-45]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-45]     from .motor_ctrl import MotorCtrl
[driver-45]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-45]     from ..utils import cffirmware
[driver-45]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-45]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-45] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-45] terminate called after throwing an instance of 'std::runtime_error'
[driver-45]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-41] Traceback (most recent call last):
[driver-41]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-41]     import cffirmware
[driver-41] ModuleNotFoundError: No module named 'cffirmware'
[driver-41] 
[driver-41] During handling of the above exception, another exception occurred:
[driver-41] 
[driver-41] Traceback (most recent call last):
[driver-41]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-41]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-41]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-41]     from .motor_ctrl import MotorCtrl
[driver-41]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-41]     from ..utils import cffirmware
[driver-41]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-41]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-41] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-41] terminate called after throwing an instance of 'std::runtime_error'
[driver-41]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-3] Traceback (most recent call last):
[driver-3]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-3]     import cffirmware
[driver-3] ModuleNotFoundError: No module named 'cffirmware'
[driver-3] 
[driver-3] During handling of the above exception, another exception occurred:
[driver-3] 
[driver-3] Traceback (most recent call last):
[driver-3]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-3]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-3]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-3]     from .motor_ctrl import MotorCtrl
[driver-3]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-3]     from ..utils import cffirmware
[driver-3]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-3]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-3] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-3] terminate called after throwing an instance of 'std::runtime_error'
[driver-3]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[driver-8] Traceback (most recent call last):
[driver-8]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 6, in <module>
[driver-8]     import cffirmware
[driver-8] ModuleNotFoundError: No module named 'cffirmware'
[driver-8] 
[driver-8] During handling of the above exception, another exception occurred:
[driver-8] 
[driver-8] Traceback (most recent call last):
[driver-8]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/__init__.py", line 6, in <module>
[driver-8]     from .motor_ctrl_fpqr import MotorCtrlFPQR
[driver-8]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl_fpqr.py", line 9, in <module>
[driver-8]     from .motor_ctrl import MotorCtrl
[driver-8]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/webots_plugin/motor_ctrl.py", line 11, in <module>
[driver-8]     from ..utils import cffirmware
[driver-8]   File "/home/yz317/dev_ws/build/crazychoir/crazychoir/utils/__init__.py", line 8, in <module>
[driver-8]     raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')
[driver-8] ImportError: Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py
[driver-8] terminate called after throwing an instance of 'std::runtime_error'
[driver-8]   what():  The crazychoir.webots_plugin.MotorCtrlFPQR plugin cannot be found (C++ or Python).
[ERROR] [driver-8]: process has died [pid 976938, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_1 --params-file /tmp/launch_params_fyz8i4lz'].
[ERROR] [driver-29]: process has died [pid 976999, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_6 --params-file /tmp/launch_params_kdbrdv3u'].
[ERROR] [driver-37]: process has died [pid 977022, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_8 --params-file /tmp/launch_params_bs_8a23q'].
[ERROR] [driver-13]: process has died [pid 976950, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_2 --params-file /tmp/launch_params_c094o10i'].
[crazychoir_formation_webots_guidance-23] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992786.177614183] [agent_4.guidance]: Guidance 4 started
[ERROR] [driver-21]: process has died [pid 976981, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_4 --params-file /tmp/launch_params_tb4wju67'].
[crazychoir_formation_webots_guidance-23] [INFO] [1688992786.203342067] [agent_4.guidance]: Go!
[ERROR] [driver-25]: process has died [pid 976990, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_5 --params-file /tmp/launch_params_586g7p84'].
[ERROR] [driver-17]: process has died [pid 976963, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_3 --params-file /tmp/launch_params_sa8jkoq_'].
[ERROR] [driver-33]: process has died [pid 977012, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_7 --params-file /tmp/launch_params_bja7xwyw'].
[ERROR] [driver-45]: process has died [pid 977045, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_10 --params-file /tmp/launch_params_cjqibysy'].
[ERROR] [driver-3]: process has died [pid 976926, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_0 --params-file /tmp/launch_params_n0b33e4q'].
[ERROR] [driver-41]: process has died [pid 977031, exit code -6, cmd '/home/yz317/dev_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args -r __ns:=/agent_9 --params-file /tmp/launch_params_0oha8uq8'].
[crazychoir_formation_webots_guidance-19] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992786.856555690] [agent_3.guidance]: Guidance 3 started
[crazychoir_formation_webots_guidance-19] [INFO] [1688992786.924082564] [agent_3.guidance]: Go!
[crazychoir_formation_webots_guidance-35] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.114164591] [agent_7.guidance]: Guidance 7 started
[crazychoir_formation_webots_guidance-35] [INFO] [1688992787.134004026] [agent_7.guidance]: Go!
[crazychoir_formation_webots_guidance-15] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.163215605] [agent_2.guidance]: Guidance 2 started
[crazychoir_formation_webots_guidance-27] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.179417356] [agent_5.guidance]: Guidance 5 started
[crazychoir_formation_webots_guidance-15] [INFO] [1688992787.194351419] [agent_2.guidance]: Go!
[crazychoir_formation_webots_guidance-27] [INFO] [1688992787.195905529] [agent_5.guidance]: Go!
[crazychoir_formation_webots_guidance-31] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.206421745] [agent_6.guidance]: Guidance 6 started
[crazychoir_formation_webots_guidance-43] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.207313155] [agent_9.guidance]: Guidance 9 started
[crazychoir_formation_webots_guidance-5] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.213960319] [agent_0.guidance]: Guidance 0 started
[crazychoir_formation_webots_guidance-43] [INFO] [1688992787.226814440] [agent_9.guidance]: Go!
[crazychoir_formation_webots_guidance-47] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.229273597] [agent_10.guidance]: Guidance 10 started
[crazychoir_formation_webots_guidance-39] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.229843411] [agent_8.guidance]: Guidance 8 started
[crazychoir_formation_webots_guidance-5] [INFO] [1688992787.230105615] [agent_0.guidance]: Go!
[crazychoir_formation_webots_guidance-31] [INFO] [1688992787.233746995] [agent_6.guidance]: Go!
[crazychoir_formation_webots_guidance-47] [INFO] [1688992787.240172330] [agent_10.guidance]: Go!
[crazychoir_formation_webots_guidance-39] [INFO] [1688992787.242289010] [agent_8.guidance]: Go!
[crazychoir_formation_webots_guidance-10] Invalid MIT-MAGIC-COOKIE-1 key[INFO] [1688992787.265552736] [agent_1.guidance]: Guidance 1 started
[crazychoir_formation_webots_guidance-10] [INFO] [1688992787.274278660] [agent_1.guidance]: Go!

`

In addition, this is our init file under the `~/dev_ws/src/crazychoir/crazychoir/utils/__init__.py` path
`# Change this path to your crazyflie-firmware folder
import sys
sys.path.append('~/dev_ws/src/crazyflie-firmware/build')

try:
    import cffirmware
except ImportError:
    raise ImportError('Set your crazyflie-firmware folder path in crazychoir/utils/__init__.py')`

Please let me know if I need to make any changes to fix this problem.
Calvin

**Comment by lorenzopichierri** [comment]
Hi Calvin,

Thank you for your interest in our package! To solve the `ModuleNotFoundError: No module named 'cffirmware'` issue, please make sure you have correctly set up the Crazyflie firmware bindings as described in our [installation guide](https://opt4smart.github.io/crazychoir/installation). If the problem persists, do not hesitate to contact us again!

Best regards,
Lorenzo
